### ISSUE TITLE
Questions regarding creating the NIDM file...

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/kwyk2nidm#3]
@satra , thanks for adding the "Convert the volume result file into NIDM" instructions.

There are 2 steps listed (pip install, and the docker). Are these steps sequential (i.e. do 1 then 2), or is this an either or (i.e. do it the pip install way, OR do it the docker way)? I'm assuming either, but want confirmation. If so, I may adjust the instructions a bit.

Assuming the either, IF I'm doing the pip install way, in the command:
    $ kwyk2nidm -f kwyk_stats_file   
I'm assuming that the 'kwyk_stats_file' is the output of the kwykput.sh. What/where does the NIDM-output go? 

Finally, the last sentence of the section isn't complete: "This will generate a"

Thanks.

**Comment by satra** [comment]
it's either or.  the nidm file is generated in the current working directory.

**Comment by dnkennedy** [comment]
I guess I will learn when I try it, but the output file will be called what?
